import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import * as model from '../src/model.js';

const grouped = model.groupResourcesByMonth([{ id:'a',published_on:'2026-09-14'},{id:'b',published_on:'2026-09-14'},{id:'c',published_on:'2026-10-01'}]);
assert.equal(grouped['2026']['09']['14'].length,2); assert.equal(grouped['2026']['10']['01'][0].id,'c');
assert.equal(model.matchesQuery({title:'기술노동자 권력의 부상과 몰락'},'기술노동',['title']),true); assert.equal(model.matchesQuery({title:'다른 글'},'기술노동',['title']),false);
assert.equal(model.safeHttpUrl('https://example.com/a'),'https://example.com/a'); assert.equal(model.safeHttpUrl('javascript:alert(1)'),''); assert.equal(model.safeHttpUrl('not a url'),'');
const now=Date.UTC(2026,8,17,12,0,0), thirtyDaysLater=now+30*24*60*60*1000;
assert.equal(typeof model.rememberLoginUntil,'function'); assert.equal(model.rememberLoginUntil(now),thirtyDaysLater); assert.equal(model.isRememberedLoginValid(String(thirtyDaysLater),now+1),true); assert.equal(model.isRememberedLoginValid(String(thirtyDaysLater),thirtyDaysLater),false);
assert.equal(model.isOAuthCallback('?code=abc123'),true); assert.deepEqual(model.enabledAuthProviders(),['google']);

const readingTools=await import('../src/reading-tools.js');
assert.match(readingTools.importStatusMessage('metadata_only'),/본문/); assert.throws(()=>readingTools.normalizeAiReadResult({claims:'bad'}));
const apiSource=readFileSync(new URL('../src/api.js',import.meta.url),'utf8');
const importUiSource=readFileSync(new URL('../src/reading-import-ui.js',import.meta.url),'utf8');
const aiUiSource=readFileSync(new URL('../src/reading-ai-ui.js',import.meta.url),'utf8');
const entryFlowSource=readFileSync(new URL('../src/reading-entry-flow.js',import.meta.url),'utf8');
const authEnhanceSource=readFileSync(new URL('../src/auth-enhance.js',import.meta.url),'utf8');
const appEntrySource=readFileSync(new URL('../src/app-entry.js',import.meta.url),'utf8');
const stylesSource=readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const importFn=readFileSync(new URL('../supabase/functions/rtw-url-import/index.ts',import.meta.url),'utf8');
const aiFn=readFileSync(new URL('../supabase/functions/rtw-ai-read/index.ts',import.meta.url),'utf8');
assert.equal(apiSource.includes('signInWithPassword'),false); assert.equal(apiSource.includes('auth.signUp'),false); assert.match(authEnhanceSource,/Google로 로그인/);
assert.match(importFn,/Authorization/); assert.equal(/owner_user_id|assertRtwOwner/.test(importFn),false,'URL import supports every authenticated user'); assert.match(apiSource,/export async function importResourceUrl/); assert.match(importUiSource,/URL로 가져오기/);
assert.match(aiFn,/OPENAI_API_KEY/); assert.match(aiFn,/store:\s*false/); assert.match(aiFn,/\.eq\('owner_id', user\.id\)/,'AI reads only the signed-in user workspace'); assert.match(apiSource,/export async function analyzeResource/); assert.match(aiUiSource,/GPT로 읽기/);
assert.match(apiSource,/export async function updateResource/,'saved reading resources can be edited later');
const mainSource=readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
assert.match(mainSource,/원문·정보 수정/,'resource detail exposes edit action');
assert.match(mainSource,/id="resource-edit-form"/,'resource detail has edit form');
assert.match(mainSource,/api\.updateResource\(id, form\)/,'resource edits are persisted');
assert.match(mainSource,/function bindNoteActions\(\)/,'note actions share one event binder');
assert.match(mainSource,/function noteTypeOptions\(/,'note type choices use one shared renderer');
assert.match(mainSource,/note-type-manage-toggle/,'notes expose custom type management');
assert.match(apiSource,/export async function createNoteType/,'custom note types can be created');
assert.match(apiSource,/export async function deleteNoteType/,'custom note types can be removed');
assert.match(mainSource,/api\.updateNote\(/,'notes can be edited');
assert.match(mainSource,/api\.deleteNote\(/,'notes can be deleted');
assert.match(mainSource,/data-note-record-edit/,'full note records expose edit controls');
assert.match(mainSource,/data-note-delete/,'note records expose delete controls');
assert.match(mainSource,/data-note-target/,'note summaries link to their full note record');
assert.match(mainSource,/targetNoteId[\s\S]*scrollIntoView/,'linked notes open and scroll into view');
assert.match(mainSource,/data-note-resource/,'note links retain their source resource');
assert.match(mainSource,/resourceId[\s\S]*resourceDetailView\(resourceId\)/,'resource-linked notes route to their article');
assert.match(mainSource,/function noteParts\(note\)/,'quoted note parsing has one shared implementation');
assert.match(mainSource,/note-quote-preview/,'quoted notes render quotations separately');
assert.match(mainSource,/note-memo-preview/,'quoted notes render the user memo once');
assert.match(mainSource,/note-quote-full[\s\S]*note-memo-full/,'opened quoted notes reveal full quote and memo separately');
assert.match(mainSource,/function homeView\(\)[\s\S]*?bindCommon\(\);[\s\S]*?bindResourceBookmarkButtons\(\);/,'home resource stars use the shared bookmark toggle binding');
assert.match(entryFlowSource,/id="home-quick-add"/); assert.match(entryFlowSource,/\?new=1/); assert.match(entryFlowSource,/\+ 새 자료/); assert.match(importUiSource,/URLSearchParams/); assert.match(importUiSource,/requestSubmit/); assert.match(appEntrySource,/reading-entry-flow\.js/);

// Shared visual rhythm and mobile layout contract.
assert.match(stylesSource,/--space-1:\s*8px/,'8px spacing token');
assert.match(stylesSource,/--space-2:\s*12px/,'12px spacing token');
assert.match(stylesSource,/--space-3:\s*16px/,'16px spacing token');
assert.match(stylesSource,/--space-section:\s*20px/,'20px section/card gap token');
assert.match(stylesSource,/--space-large:\s*24px/,'24px large spacing token');
assert.match(stylesSource,/\.home-stack\{[^}]*gap:var\(--space-section\)/,'home cards use one shared stack gap');
assert.match(stylesSource,/:root\{--header-h:51px;--header-top:-44px\}\s*\.topbar\{top:var\(--header-top\)\}\s*html\{scroll-padding-top:calc\(var\(--header-h\) \+ 12px\)\}/,'mobile header covers content with the menu row only, and scroll targets clear it');
assert.match(stylesSource,/@media\(max-width:760px\)[\s\S]*\.userbar span\{[^}]*display:none/,'mobile hides redundant email');
assert.match(stylesSource,/@media\(max-width:760px\)[\s\S]*\.nav a\{[^}]*min-height:40px/,'mobile nav has adequate touch targets');
assert.match(stylesSource,/@media\(max-width:760px\)[\s\S]*\.page\{[^}]*padding-top:var\(--space-large\)/,'mobile page starts clear of header');
assert.match(stylesSource,/overflow-wrap:anywhere/,'long content must not create horizontal overflow');
assert.match(stylesSource,/\.empty\{[^}]*padding:var\(--space-3\) 0/,'empty states stay compact');
assert.match(aiUiSource,/function textSection/,'AI results render as selectable text sections');
assert.equal(/메모로 저장|질문으로 저장|>연결</.test(aiUiSource),false,'AI result save/connect buttons are removed');
assert.equal(/createNote|createQuestion|addRelation/.test(aiUiSource),false,'AI reading UI does not write records directly');

console.log('model tests passed');
