# Deploying this configuration transfers read.bokdoong.com to rtw-router.
name = "rtw-router"
main = "rtw-router.mjs"
compatibility_date = "2026-09-20"
workers_dev = false

[[routes]]
pattern = "read-test.bokdoong.com"
custom_domain = true

[[routes]]
pattern = "read.bokdoong.com"
custom_domain = true
